server {
    listen 80;

    location / {
      proxy_pass http://ticket-master-ui:80/;
      # proxy_pass http://ticket-master-ui:5713; # for local development, run react with `npm run start:docker`
    }

    location /api/ {
        proxy_pass http://ticket-master-gateway:8000;
    }

    # only for local development anyways - in prod not relevant (using k8s)
    client_max_body_size 1000M;
    client_body_buffer_size 1000M;
}
